require("prototypes.avatar-animations")
require("prototypes.entities.assembly")
require("prototypes.entities.avatar")
require("prototypes.entities.enterable-entities")
require("prototypes.entities.dead-player")
require("prototypes.hotkey")
require("prototypes.items.items")
require("prototypes.items.intermediates")
require("prototypes.items.item-groups")
require("prototypes.recipes")
require("prototypes.technologies.technologies")
require("styles.styles")


require("prototypes.mod-integration.angels")
require("prototypes.mod-integration.bobs")