require("prototypes.entities.avatar")
require("prototypes.entities.enterable-entities")
require("prototypes.entities.fake-player")
require("prototypes.hotkey")
require("prototypes.items.items")
require("prototypes.items.intermediates")
require("prototypes.items.item-groups")
require("prototypes.recipes")
require("prototypes.technologies.technologies")
require("styles.styles")


require("prototypes.mod-integration.util")
require("prototypes.mod-integration.aai-programmable-vehicles")
--require("prototypes.mod-integration.angels")
--require("prototypes.mod-integration.bobs")
require("prototypes.mod-integration.space-age")
--require("prototypes.mod-integration.space-exploration")
